### ISSUE TITLE
Could not find a suitable provider for quota

### ISSUE THREAD

**Issue by kwisatz** [DimitriSteyaert/puppet-quota#4]
I'm running into this problem where the quota provider is being created in `/var/lib/puppet/lib/puppet/provider`  but then the call to it still fails with:

```
Notice: /File[/var/lib/puppet/lib/puppet/type/quota.rb]/ensure: defined content as '{md5}a7560639c796d514c47be2c301a607c9'
Notice: /File[/var/lib/puppet/lib/puppet/provider/quota]/ensure: created
Notice: /File[/var/lib/puppet/lib/puppet/provider/quota/quota.rb]/ensure: defined content as '{md5}397f2fcd71a8cf2d004f1cd74249bd05'
[…]
Notice: Stage[main]: Would have triggered 'refresh' from 17 events
Error: Could not find a suitable provider for quota
Notice: Finished catalog run in 4.51 seconds
```

The only similar issues I've found are https://github.com/puppetlabs/puppetlabs-aws/issues/298 (or https://ask.puppet.com/question/25719/getting-error-could-not-find-a-suitable-provider-error-message-when-puppetlabs-aws-module/) and I'm not sure if installing some gem would the correct solution in this case?

**Comment by kwisatz** [comment]
OK, the riddle's solution might be this:

```
root@server:/var/lib/puppet/lib# puppet resource --debug quota
Debug: Runtime environment: puppet_version=3.7.2, ruby_version=2.1.5, run_mode=user, default_encoding=UTF-8
Debug: Puppet::Type::Quota::ProviderQuota: file quotatool does not exist
Debug: Puppet::Type::Quota::ProviderQuota: file quotatool does not exist
```

It doesn't say this in https://github.com/DimitriSteyaert/puppet-quota#setup-requirements though… and that binary didn't come with installing the `quota` package.

**Comment by DimitriSteyaert** [comment]
Hi, it's been years since I have worked with Puppet so this plugin is from a lot of versions ago. So I'm afraid that I won't be able to provide you with a suitable answer to your question.

But indeed, from what I recall the command quotatool needs to be installed on your server.

**Comment by kwisatz** [comment]
I can see it's supposed to be installed… and I think I might have found the issue on my side ;)
Well, the version is fine in this case, since the puppet version running here isn't the most recent either.

**Comment by DimitriSteyaert** [comment]
Oh that's great then. I'm closing this thread 😄

**Comment by kwisatz** [comment]
I was going to close it anyway once I'd made sure that what I believe to be my mistake actually is.
Would you care for a PR to extend the README in that regard?

**Comment by DimitriSteyaert** [comment]
Yeah sure, go ahead. I'll merge
